### ISSUE TITLE
No bundle url present

### ISSUE THREAD

**Issue by tweetzal** [rubygarage/react-native-firebase-chat#5]
Having the following issue in simulator for iOS : 
`Make sure you're running a packager server ......`

See screenshot

<img width="678" alt="screen shot 2018-02-20 at 13 15 29" src="https://user-images.githubusercontent.com/2478550/36425922-5c7d1a30-1640-11e8-9da4-6cc59949e51f.png">

**Comment by ahajji87** [comment]
yarn install or npm install may fix it.

**Comment by drew-sullivan** [comment]
I'm having the same issue. I tried npm install and yarn install. Same screen as above.

**Comment by drew-sullivan** [comment]
Has anyone tried loading this app up with Expo? Maybe that would make this part easier...?

**Comment by plzen** [comment]
Looks like regular issue with React Native.

https://github.com/facebook/react-native/issues/12754
