### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AnthonyNTK** [rubygarage/react-native-firebase-chat#6]
I simply clone the project then
`npm install`
after that
`react-native run-android`

i am running the app in real device with below spec
```
Android 7.1.1
Sony Xperia X
```

Development Env:
`Windows 10`

**Comment by plzen** [comment]
You also need to change Firebase config in file `app/configs/firebase.js`

**Comment by vincentmuriuki** [comment]
What exactly should be the content of the firebase.js file
